wri/cities-cif

city_metrix/layers/osm_open_space.py
=> add open space layer from osm

city_metrix/__init__.py, city_metrix/layers/__init__.py, city_metrix/layers/albedo.py, city_metrix/layers/esa_world_cover.py, city_metrix/layers/land_surface_temperature.py, city_metrix/layers/landsat_collection_2.py, city_metrix/layers/natural_areas.py, city_metrix/layers/smart_cities_lulc.py, city_metrix/layers/tree_cover.py, notebooks/tutorial.ipynb, setup.py, tests/layers.py, tests/metrics.py
- Instead of relying on dask/coiled and AWS public satellite imagery for albedo and LST, use Xee since it's quite fast and requires less set up/permissions. The numbers also match the GEE scripts better.
- Suppress warnings from Xee.
- Update tutorial notebook with changes.
Automated and manual tests.
=> [CIF-140] Use Xee everywhere

README.md, docs/developer.md
=> draft developer guide

city_metrix/__init__.py, city_metrix/layers/__init__.py, city_metrix/layers/esa_world_cover.py, city_metrix/layers/layer.py, city_metrix/layers/natural_areas.py, city_metrix/layers/open_street_map.py, city_metrix/layers/urban_land_use.py, city_metrix/metrics.py
=> Selective update of files for natural areas, osm, and ulu

city_metrix/layers/__init__.py, city_metrix/layers/world_pop.py
=> [CIF-148] add world pop layer

city_metrix/layers/open_street_map.py
update osm layer to handle InsufficientResponseError
osm layer won't get an error if no feature within the bbox
=> update osm layer to handle InsufficientResponseError

README.md, city_metrix/layers/__init__.py, city_metrix/layers/open_buildings.py, docs/developer.md, environment.yml, notebooks/tutorial/get layers.ipynb, tests/layers.py
Adds a new `OpenBuildings` layer function to get data from https://gee-community-catalog.org/projects/global_buildings/
1. Run the test
```
cd tests
pytest layers.py::test_openbuildings
```
2. Try the function on a location you know
* See the "get layers" notebook for an example
JIRA issue: https://gfw.atlassian.net/browse/CIF-168
=> [CIF-168] add open buildings layer

environment.yml
=> add boto3 in yml file

tests/test_layers.py, tests/test_methods.py
=> Initial work on expanding coverage.

city_metrix/layers/open_street_map.py, environment.yml
=> upgrade osmnx version

city_metrix/layers/era_5_hottest_day.py
Fix for `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'download_0.nc'` on Windows.
per https://github.com/pydata/xarray/issues/1629
=> Use context manager to open and close nc file

scripts/calculate_indicators.py
=> Cif 284 - layers and metrics script

city_metrix/layers/era_5_hottest_day.py, city_metrix/metrics/era_5_met_preprocessing.py, environment.yml, setup.py
https://gfw.atlassian.net/browse/CIF-322
=> CIF-322 fix era5 issue

city_metrix/layers/era_5_hottest_day.py, tests/test_metrics.py
-Yes, CIF 346
remove nan values
on local machine
=> Fixed missing values in ERA5 data

README.md, city_metrix/layers/cams.py
https://gfw.atlassian.net/browse/CIF-352
=> CIF-352 use grib for cams

city_metrix/layers/cams.py, city_metrix/layers/era_5_hottest_day.py
https://gfw.atlassian.net/browse/CIF-355
=> CIF-355 directly specify the url for cdsapi

city_metrix/layers/layer_geometry.py, tests/test_layer_parameters.py
=> added pre-buffering of GEE selection area

city_metrix/layers/__init__.py, city_metrix/layers/open_buildings.py, city_metrix/layers/overture_buildings_w_height.py, city_metrix/layers/overture_buildings_w_height_raster.py, city_metrix/layers/ut_globus.py, setup.py, tests/resources/conftest.py, tests/resources/layer_dumps/test_write_all_layers.py, tests/test_layers.py
https://gfw.atlassian.net/browse/CDB-194
Add 3 layers - 
__ut_globus__: original UTGLOBUS data in polygon dataframe
__overture_buildings_w_height__: overture building with height from UTGLOBUS if available, in polygon dataframe
__overture_buildings_w_height_raster__: overture building with height from UTGLOBUS if available, in raster dataarray. Spatial resolution of 1m, building without height data has value 0, and non-building NA has value -999.
=> CDB-194 add ut globus layer

tests/resources/metrics_dumps/test_write_all_metrics.py, tests/test_layers.py, tests/test_metrics.py
=> Cdb 242 add value based tests for cif

ReleaseNotes.md, city_metrix/layers/overture_buildings_dsm.py, city_metrix/metrix_model.py, city_metrix/ut_globus_city_handler/ut_globus_city_handler.py
Rewrote layer to avoid mismatches between adjacent tiles.
=> Cdb 303 scoping tiling effects with building heights

city_metrix/layers/overture_buildings_dsm.py, tests/resources/layer_dumps/test_write_all_layers_by_city.py
Minor change for documentation purposes.
=> improved code documentation

ReleaseNotes.md, city_metrix/layers/__init__.py, city_metrix/layers/open_urban.py, tests/resources/layer_dumps/test_write_very_slow_layers.py, tests/test_layers.py
https://gfw.atlassian.net/browse/CDB-306
Moved OpenUrban class from C-TCM to CIF and added additional CIF embellishment.
Former location: https://github.com/wri/cities-thermal-comfort-modeling/blob/main/src/workers/open_urban.py
=> Cdb 306 explore moving open urban class from c tcm to cif

city_metrix/layers/overture_buildings_dsm.py, tests/test_layers.py
See https://gfw.atlassian.net/browse/CDB-310 
This is a straight-forward replacement of NasaDem with FabDem. General agreement on Cities Heat team is that FabDEM is the better choice.
I also standardized some variable names.
=> replaced nasa dem with fabdem

city_metrix/layers/average_net_building_height.py, city_metrix/layers/overture_buildings_w_height.py, city_metrix/metrix_model.py, tests/resources/layer_dumps/test_write_all_layers_by_city.py, tests/resources/layer_dumps/test_write_layer_variants.py, tests/test_layer_parameters.py, tests/tools/general_tools.py
See https://gfw.atlassian.net/browse/CDB-301
=> Cdb 301 add ghsl building height to footprints that lack height data

city_metrix/layers/era_5_hottest_day.py, tests/test_layer_variants.py
https://gfw.atlassian.net/browse/CDB-399
=> CDB-399 Enable half hour UTC offsets

ReleaseNotes.md, city_metrix/layers/era_5_hottest_day.py, city_metrix/metrics/era_5_met_preprocessing_umep.py, city_metrix/metrics/era_5_met_preprocessing_upenn.py, environment.yml, setup.py, tests/resources/file_caching/test_layer_caching.py, tests/resources/metrics_dumps/test_write_all_metrics.py, tests/resources/metrics_dumps/test_write_all_metrics_by_city.py, tests/test_layer_variants.py, tests/test_layers.py, tests/test_metrics.py
See https://gfw.atlassian.net/browse/CDB-423
1. added utc_offset parameter to ERA5 classes
2. removed timezonefinder dependency
=> added utc_offset parameter to ERA5 classes

city_metrix/metrix_model.py, tests/resources/layer_dumps/test_write_very_slow_layers.py, tests/resources/metrics_dumps/test_write_all_metrics.py, tests/resources/metrics_dumps/test_write_all_metrics_by_city.py, tests/resources/metrics_dumps/test_write_metric_variants.py, tests/tools/general_tools.py
https://gfw.atlassian.net/browse/CDB-430
=> CDB-430 use development env for metrics_dumps and layer_dumps tests

ReleaseNotes.md, city_metrix/layers/albedo.py, city_metrix/layers/albedo_cloud_masked.py, tests/test_file_naming.py, tests/test_layer_parameters.py, tests/test_layer_variants.py, tests/test_layers.py
https://gfw.atlassian.net/browse/CDB-429
=> added default date range for albedo layers

city_metrix/metrix_model.py, tests/test_layer_geometry.py
https://gfw.atlassian.net/browse/CDB-448
Increase maximum limit for cell count on a side from 100 to 1000.
=> increasing maximum cell count on a side to 1,000 cells

city_metrix/metrix_model.py, environment.yml, tests/resources/file_caching/test_cache_metrics_by_city.py, tests/test_layer_geometry.py, tests/test_metrics_per_city.py
=> fixed bug in defining city aoi boundary

city_metrix/constants.py, city_metrix/metrix_model.py
=> defined notification file name in constants

city_metrix/layers/__init__.py, city_metrix/layers/era_5_hottest_day_gee.py, city_metrix/metrics/__init__.py, city_metrix/metrics/era_5_met_preprocessing_umep_gee.py, city_metrix/metrics/era_5_met_preprocessing_upenn_gee.py, city_metrix/metrix_model.py, tests/resources/layer_dumps/test_write_all_layers_by_city.py, tests/resources/metrics_dumps/test_write_all_metrics.py, tests/resources/metrics_dumps/test_write_all_metrics_by_city.py, tests/test_layers.py, tests/test_metrics.py
https://gfw.atlassian.net/browse/CDB-456
=> update to use era5 data from gee

environment.yml, setup.py, tests/test_layer_variants.py, tests/test_layers.py
=> updating for Overturemaps version
